export const GET_INVOICES = "GET_INVOICES";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const SET_LOADING = "SET_LOADING";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
